In [ ]:
#importing numpy
import numpy as np


In [ ]:
#first array group
first_array_group = np.array([1,2,3,4,5])
first_array_group

array([1, 2, 3, 4, 5])

In [ ]:
#zeros array
zeros_array = np.zeros((2,2))
zeros_array

array([[0., 0.],
       [0., 0.]])

In [ ]:
#ones array
ones_array = np.ones((2,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#arrange arrays
aranged_array = np.arange(18)
aranged_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
#reshape
aranged_array.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [ ]:
#3D array
new_array = np.arange(27).reshape(3,3,3)
new_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
new_array.shape

(3, 3, 3)

In [ ]:
#one D array
one_d_array = np.array([x for x in range(1,10)])
one_d_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#convert above to 2D
one_d_array.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#3D array
three_d_array = np.array([x for x in range(1,13)])
three_d_array.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#change the above
three_d_array.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
#in large datasets where dimensions are dynamic in nature
three_d_array.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#flatten a 3D array
flattened_array = three_d_array.reshape(3,2,2)
flattened_array.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#Arithmatic operations
A = ([[1,1,1],[2,2,2]])
B = ([3,2,3])

A

[[1, 1, 1], [2, 2, 2]]

In [ ]:
B

[3, 2, 3]

In [ ]:
np.add(A,B)

array([[4, 3, 4],
       [5, 4, 5]])

In [ ]:
np.subtract(B,A)

array([[2, 1, 2],
       [1, 0, 1]])

In [ ]:
np.divide(B,A)

array([[3. , 2. , 3. ],
       [1.5, 1. , 1.5]])

In [ ]:
np.multiply(A,B)

array([[3, 2, 3],
       [6, 4, 6]])

In [73]:
y = np.power(A,B)
y

array([[1, 1, 1],
       [8, 4, 8]])

In [74]:
#slicing: second row from second column
y[1,1:]

array([4, 8])

Conditional statements

In [ ]:
#will print odd and even 
x = np.array([i for i in range(6)])
x

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.where(x%2 == 0 ,"even", "odd")

array(['even', 'odd', 'even', 'odd', 'even', 'odd'], dtype='<U4')

In [ ]:
condition = [x<2,x>2]
do = ["child", "adult"]

In [ ]:
np.select(condition, do, default="teenager")

array(['child', 'child', 'teenager', 'adult', 'adult', 'adult'],
      dtype='<U8')